### ISSUE TITLE
IOS - Chrome is detected as 'Flash isSupported'?

### ISSUE THREAD

**Issue by poplark** [videojs/videojs-flash#142]
**Description**

When I use videojs and videojs-flash to play RTMP on Desktop and HLS on Mobile, I cannot get the Chrome to play the video on Mobile. And if I invoke the function `isSupported`, the result is `true`. So I think the videojs-flash works in IOS, but, should it?

**Versions**

IOS - 12.4.1
Chrome - 77.0.3865.69
video.js - 7.6.0
videojs-flash - 2.2.0

**Comment by gkatsev** [comment]
Flash doesn't work on mobile devices, I would recommend moving away from flash altogether as all browsers now have it disabled by default.
However, it's returning true because for Chrome we ended up disabling checking whether it works and just assume it works and hope that the user sees the little puzzle piece icon for plugins to enable flash. However, it sounds like we need to also verify we're not on a mobile device.

**Comment by gkatsev** [comment]
I have a fix for it in #143.
