### ISSUE TITLE
Incompatible with video.js 6.2.8

### ISSUE THREAD

**Issue by ethernetweb** [videojs/videojs-flash#35]
Sorry for not using the template, however the issue is relatively simple.

This version of videojs-flash does not function with the most recent version of video.js 6.2.8

Thank you for your time.

**Comment by gkatsev** [comment]
Can you please elaborate on "does not function"? Are you seeing errors in the console? Is the video playing? What are you expecting to happen and what are you seeing instead? What browser are you seeing this with? Following the issue template would've saved this back-and-forth since it asks for this information.

I am able to get it to work ([example](https://output.jsbin.com/mobekix)), though, chrome pretty aggressively blocks flash but once I forcibly allowed flash, it worked just fine.

**Comment by gkatsev** [comment]
Also, does it work with earlier versions of Video.js?
Anyway, thinking about this some more, and I wonder if this isn't just #26 as well.

**Comment by ethernetweb** [comment]
Sorry for that - will be sure to be more thorough in the future. Thank you for responding, none the less.
I just read through #26 and that's EXACTLY what's happening. It does pertain to live rtmp/flv streams.

It did work on a previous version of video.js, however I don't recall what version that was (I didn't save the old version when I updated).

I believe now that this is a duplicate issue. Will close this. My apologies.

**Comment by gkatsev** [comment]
It's OK :)
Hopefully, we can figure out #26 and fix it soon.
