### ISSUE TITLE
Can this flash plugin support hls?

### ISSUE THREAD

**Issue by victoryboss** [videojs/videojs-flash#54]
hello,dose it support hls?
1、
with chrome and ie10， videojs-contrib-hls works good ,
but now have to support ie8/ie9，then back to flash
2、
I used to use videojs-flash to support hls. These are links
flashhls: http://www.flashls.org
swf github: https://github.com/mangui/flashls
these plugins need videojs version 4.6 or 4.7 or 4.8.
but not support videojs version 5 or 6.
3、
so can this amzing official flash plugin support videojs 6 and support hls ?

(thank you for your contribution.)

**Comment by mister-ben** [comment]
videojs-flash does not play HLS. The videojs-contrib-hls source handler can use the videojs-contrib-hls to play HLS, but not on old IE versions.

There's no tech or source handler maintained by the Video.js team that plays HLS on old IE. I don't know whether there is any solution that's currently maintained, especially since the demand to support these IE versions is so small.

**Comment by victoryboss** [comment]
Thank you for your answer. 
Even though IE8 is used by just 8% of people , in China the number of users reach millions . 
Now I have to switch videojs version according  to the browser version.
Thank you for your answer.
谢谢你！
