### ISSUE TITLE
Update package.json to use peerDependencies instead of dependencies for video.js

### ISSUE THREAD

**Issue by confusingstraw** [videojs/videojs-flash#92]
## Description
When using the videojs-flash tech in an environment that respects node_modules structure (webpack, for example), the dependency structure will result in duplicate instances of VideoJS being installed, causing the Flash tech to be registered against the wrong instance of VideoJS at runtime.

## Steps to reproduce
1. Install video.js and videojs-flash
2. Import them in a Webpack project
3. Attempt to use the 'Flash' tech

### Expected
A working instance of the Flash tech being registered

### Actual
The Flash tech being registered to a private instance of video.js

## Additional Information
This should be easy to mitigate by using the peerDependencies field of the package.json. This will tell npm/yarn to use whatever version of video.js the client has installed, and will warn them if they do not have a compatible version.

#### videojs
7.1.2

#### browsers
All

#### OSes
All

### plugins
videojs-flash

**Comment by gkatsev** [comment]
videojs-flash has a pretty broad range and npm should be able to resolve a single version of Video.js assuming you depend on a v6 or v7 version of Video.js.

Historically, we didn't use peerDep because npm's support of peer deps was bad and caused greater issues than they solved. It is, however, probably time for us to revisit peerDeps in light of various issues people have been having lately.

**Comment by rgfoley** [comment]
I definitely agree that NPM/Yarn should be able to dedupe the dependencies, but in practice I found that even with Video.js 7.1.3 installed, videojs-flash installed its own copy of 7.1.2.

**Comment by gkatsev** [comment]
Weird, have you tried running `npm dedupe`? Does that keep two versions?
